### ISSUE TITLE
Week 1 Review Ticket - Punnu

### ISSUE THREAD

**Issue by PunarvasuS** [PunarvasuS/PopcornCritics#20]
# SCORE = 4.7/5, REVIEWED BY TANAY RAYAVARAPU FOR PUNARVASU SANGAM
## Individual GitHub pages (3 points)
- GitHub page for Test Prep study, requiring [5.3, 5.4 notes and actions.](https://punarvasus.github.io/DataStructures/tps)
  - [x] One Check 5.3
  - [x] One Check 5.4
- GitHub page that [documents key learnings and code snippets using GitHub and replit.](https://punarvasus.github.io/DataStructures/project/)
  - [InfoDB lists](https://replit.com/@LordPotashmallo/Menu#InfoDb.py)
- [x] One Check for New Data, minimum of 4 items
  - [InfoDB loops](https://replit.com/@LordPotashmallo/Menu#InfoDb.py)
- [x] One Check For Loop running and sensible output
- [x] One Check While Loop running and sensible output
- [x] One Check Recursion running and sensible output
  - Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
- Four checks: 
    - [x] Algorithm and code with comments
    - [x] Prints result
    - [x] Prints Complete List
    - [x] Work on complex sequence with multiple words, spaces, special characters
- [x] One check: comments and documentation throughout

**Comment by TANAY101405** [comment]
# Week 1 Individual Score = 2.85/3
# Individual Checks = ~/11

### -0.15 on Individual score because there could be more evidence of code snippets and comments. Also, for your github Pages, I liked how you organized everything for the replit challenges by adding in different tabs as soon as you click on it.

- GitHub page for Test Prep study (Checks: 2/2)
- [ ] One Check 5.3
- [ ] One Check 5.4
- Pages are well documented with notes and answers to github actions that are thoroughly completed. I liked your answer to the crowdsourcing question about the movie idea since that follows your website theme.

---------------------------------------


-GitHub page that documents key learnings and code snippets using GitHub and replit (Check Score: 9/9)
- [ ] One Check for New Data, minimum of 4 items
- [ ] One Check For Loop running and sensible output
- [ ] One Check While Loop running and sensible output
- [ ] One Check Recursion running and sensible output
- [ ] Four checks: Algorithm, code with comments, Prints result, Prints Complete List,
- [ ] One check: comments and documentation throughout
