### ISSUE TITLE
Week 2 Crossover Review

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/PopcornCritics#25]
Leave Comments Below Please :)

**Comment by jm1021** [comment]
Movies and movie subpages.   Technical pages that tell how it is done.

Hosting AWS for short term.  Not clear about purpose of Pi.

MIT license.   They allow someone else to take it over.

Wireframe show main page, learn more, movie quiz, ranking of movies.   All pages would have a learn more.

Question on Sort.  Suggesting sorting by director.

Question on using a Database.   Comment system.  Each movie had comments or reviews. 

Suggest more information on each page and details.   Seems real basic so far.   Also, show mock up of Movie versus learning example(s).

**Comment by TANAY101405** [comment]
Movie genre idea with user input reviews
- Importing reviews from other websites (IMDB, Rotten Tomatoes)

Promising ideas of using an API and database to have a comment/review section
- Might want to show a little progression with the project, such as frontend HTML page
- Colin asked a question about how they would sort the movies, genre or rating? Maybe look into that

Overall idea is good because it incorporates something everyone loves (movies) with a user interface

Interested in how you are going to teach code on one of the pages

Flowchart is done well, but you can add more of a timeline for plans/development
